### ISSUE TITLE
 Incorrect indents

### ISSUE THREAD

**Issue by MarinaShaposhnikova** [Popalay/YoCard#3]
Device :  MEIZU PRO 5
1. User has 3 cards.
2. Remove first card
3. Undo
![1](https://cloud.githubusercontent.com/assets/18406544/25431910/260b1c0a-2a8b-11e7-8703-2e5bb6d75e94.jpg)

**Comment by Popalay** [comment]
Fixed in 1e2fbaa0b0bdc693d005fd8fb8b70f0edff4284f
