### ISSUE TITLE
Wrong number of cards in tab "Holders"

### ISSUE THREAD

**Issue by MarinaShaposhnikova** [Popalay/YoCard#5]
1. Open tab "Holder"
2. User has only one card
3. Remove the card of this user
4. Undo
5. User has two cards
6. And so on

But if user has REALLY two or more cards - nothing happens

![5](https://cloud.githubusercontent.com/assets/18406544/25432993/723999c2-2a8f-11e7-9d67-e543f877accb.jpg)
![6](https://cloud.githubusercontent.com/assets/18406544/25432994/723d8348-2a8f-11e7-913f-265354d00968.jpg)

**Comment by Popalay** [comment]
Fixed in d4faab780279ca79f0f6a830dad74e17359fac40
