### ISSUE TITLE
Text with card's number disappears or changes its size

### ISSUE THREAD

**Issue by MarinaShaposhnikova** [Popalay/YoCard#6]
1. Open app
2. Remove any card
3. Undo

It happens sometimes

![7](https://cloud.githubusercontent.com/assets/18406544/25433350/d07c767a-2a90-11e7-8bdc-363d714d7e95.jpg)
![8](https://cloud.githubusercontent.com/assets/18406544/25433351/d07e3988-2a90-11e7-83c1-57a8695119f2.jpg)

**Comment by Popalay** [comment]
Fixed
